name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Build and Deploy via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST  }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -ex
            cd deploy/JuicerScribe
            git fetch origin main
            git reset --hard origin/main

            cd ~/deploy/orchestrate
            docker compose down
            docker compose build
            docker compose push
            docker compose up -d
